import { useState } from 'react';
import { useI18n } from '../lib/i18n';
import { CURRENCIES, parseAmount } from '../lib/finance';
import { api } from '../lib/api';
export function GoalEditor({ goal, currency, onSave, onClose, busy }) {
  const { t,error }=useI18n();const [message,setMessage]=useState('');
  return <form className="form" onSubmit={async e=>{e.preventDefault();if(busy)return;const f=Object.fromEntries(new FormData(e.target));try{const result=await onSave({name:f.name.trim(),targetCents:parseAmount(f.amount),currency:f.currency});if(result)setMessage(result);}catch(e){setMessage(error(e));}}}><label>{t('Nombre de tu meta','Goal name')}<input name="name" autoFocus required maxLength={60} defaultValue={goal?.name||''} placeholder={t('Ej. Mi fondo de tranquilidad','e.g. My peace-of-mind fund')}/></label><div className="form-grid"><label>{t('Monto objetivo original','Original target amount')}<input name="amount" inputMode="decimal" required defaultValue={goal?(goal.targetCents/100).toFixed(2):''} placeholder="0.00"/></label><label>{t('Moneda original','Original currency')}<select name="currency" defaultValue={goal?.currency||currency}>{Object.keys(CURRENCIES).map(c=><option key={c}>{c}</option>)}</select></label></div><p className="hint">{t('El progreso usa tu saldo total convertido. No reserva ni transfiere dinero.','Progress uses your converted total balance. It does not reserve or transfer money.')}</p>{message&&<p role="alert" className="form-error">{message}</p>}<div className="modal-actions"><button className="button secondary" type="button" disabled={busy} onClick={onClose}>{t('Cancelar','Cancel')}</button><button className="button primary" disabled={busy}>{t('Guardar meta','Save goal')}</button></div>{goal&&<button type="button" disabled={busy} className="text-button danger-text" onClick={async()=>{const result=await onSave(null);if(result)setMessage(result);}}>{t('Quitar meta (conservar movimientos)','Remove goal (keep movements)')}</button>}</form>;
}
export function PasswordForm() {
  const { t,error }=useI18n();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [success,setSuccess]=useState(false);
  return <form className="form" onSubmit={async e=>{e.preventDefault();if(busy)return;const form=e.target;const f=Object.fromEntries(new FormData(form));setMessage('');setSuccess(false);if(f.password!==f.confirm){setMessage(error('PASSWORD_MISMATCH'));return;}setBusy(true);try{await api('/auth/password',{method:'POST',body:f});setMessage(t('Contraseña actualizada. Las otras sesiones se cerraron.','Password updated. Other sessions have been signed out.'));setSuccess(true);form.reset();}catch(e){setMessage(error(e));}finally{setBusy(false);}}}><label>{t('Contraseña actual','Current password')}<input name="currentPassword" type="password" autoComplete="current-password" required maxLength={128}/></label><label>{t('Nueva contraseña','New password')}<input name="password" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label><label>{t('Confirmar nueva contraseña','Confirm new password')}<input name="confirm" type="password" autoComplete="new-password" required minLength={10} maxLength={128}/></label>{message&&<p className={success?'hint':'form-error'} role={success?'status':'alert'}>{message}</p>}<button className="button secondary" disabled={busy}>{busy?t('Guardando…','Saving…'):t('Cambiar contraseña','Change password')}</button></form>;
}
