import { useEffect, useRef, useState } from 'react';
import { useI18n } from '../lib/i18n';
import { api } from '../lib/api';
import { Icon } from './Icon';
const defaults={email:'',senders:'',amountLabel:'Monto',expenseWord:'Consumo',incomeWord:'Depósito',referenceLabel:'Referencia',decimal:'.',automatic:false,enabled:true};
const issues={
  CONFIRMATION_MISSING:['El aviso no indica explícitamente que el movimiento se completó.','The alert does not explicitly confirm the movement was completed.'],
  NOT_CONFIRMED:['Aviso no confirmado, rechazado o reversado.','Unconfirmed, declined or reversed notice.'],
  TYPE_UNCLEAR:['No se distingue una entrada de una salida.','Income versus expense is unclear.'],
  AMOUNT_UNCLEAR:['Importe o moneda ambiguos.','Amount or currency is ambiguous.'],
  SENDER_UNVERIFIED:['No se pudo verificar la firma del remitente.','The sender’s signature could not be verified.'],
  REFERENCE_MISSING:['Falta una referencia única del banco.','A unique bank reference is missing.'],
  DUPLICATE_REFERENCE:['Esta referencia ya fue registrada.','This reference was already recorded.'],
  POSSIBLE_DUPLICATE:['Ya existe un movimiento de igual importe, moneda y fecha.','A movement with the same amount, currency and date already exists.'],
  WALLET_LIMIT:['Se alcanzó un límite del registro.','A ledger limit was reached.'],
  MESSAGE_TOO_LARGE:['El correo supera el tamaño permitido.','The email exceeds the size limit.']
};
export function MailSettings({onChanged}){
 const {t,error,money,locale}=useI18n();
 const [data,setData]=useState(null),[form,setForm]=useState(defaults),[password,setPassword]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[failure,setFailure]=useState(false),[sample,setSample]=useState(''),[preview,setPreview]=useState(null),[confirm,setConfirm]=useState(null),[queued,setQueued]=useState(false);
 const alive=useRef(true),dirty=useRef(false);
 const connection=data?.connection;
 const stamp=value=>value?new Date(value).toLocaleString(locale,{dateStyle:'short',timeStyle:'short'}):t('Todavía no','Not yet');
 const issue=code=>issues[code]?t(...issues[code]):t('Revisión manual activada.','Manual review enabled.');
 function accept(next,reset=false){if(!alive.current)return;setData(next);if(reset||!dirty.current){setForm(next.connection?{...next.connection.settings,enabled:next.connection.enabled}:defaults);dirty.current=false;}}
 useEffect(()=>{alive.current=true;api('/mail').then(next=>accept(next,true)).catch(e=>{if(alive.current){setFailure(true);setMessage(error(e));}});const timer=setInterval(()=>api('/mail').then(next=>accept(next)).catch(()=>{}),10000);return()=>{alive.current=false;clearInterval(timer);};},[]);
 function change(key,value){dirty.current=true;setForm(old=>({...old,[key]:value}));setPreview(null);}
 async function run(work,success){setBusy(true);setMessage('');setConfirm(null);try{await work();setFailure(false);setMessage(success);}catch(e){setFailure(true);setMessage(error(e));}finally{if(alive.current)setBusy(false);}}
 const controlsDisabled=busy||connection?.checking;
 return <section className="panel mail-panel" id="bank-mail">
  <div className="mail-heading"><span className="icon-tile green"><Icon name="mail" size={25}/></span><div><p className="eyebrow">{t('MENOS TAREAS, MÁS CLARIDAD','LESS WORK, MORE CLARITY')}</p><h2>{t('Tu banco, en tu registro.','Your bank, in your ledger.')}</h2><p>{t('Convierte los avisos de Gmail en movimientos de Ahorra+.','Turn Gmail alerts into Ahorra+ movements.')}</p></div><span className={`mail-status ${connection?.enabled?'connected':''}`}>{connection?connection.enabled?t('Conectado','Connected'):t('En pausa','Paused'):t('Sin conectar','Not connected')}</span></div>
  <div className="mail-summary"><div><Icon name="refresh"/><span>{t('Frecuencia','Frequency')}<strong>{t('Cada hora','Every hour')}</strong></span></div><div><Icon name="check"/><span>{t('Registrados','Recorded')}<strong>{data?.counts.applied||0}</strong></span></div><div><Icon name="info"/><span>{t('Por revisar','To review')}<strong>{data?.counts.pending||0}</strong></span></div></div>
  <p className="hint mail-intro">{t('Requiere el servidor encendido e internet. Lee avisos nuevos desde la conexión inicial, incluso si ya los abriste; no modifica ni elimina correos.','Requires an online server. Reads new alerts received after connecting, even if already opened; does not modify or delete emails.')}</p>
  {message&&<p className={failure?'form-error':'notice'} role={failure?'alert':'status'}>{message}</p>}
  {data&&!data.available&&<p className="form-error">{t('Ejecuta node scripts/configure.mjs y reconstruye la app para habilitar el cifrado de Gmail.','Run node scripts/configure.mjs and rebuild the app to enable Gmail encryption.')}</p>}
  <div className="mail-columns"><div>
   <form className="form" onSubmit={e=>{e.preventDefault();if(controlsDisabled)return;run(async()=>{const next=await api(connection?'/mail/settings':'/mail/connect',{method:connection?'PUT':'POST',body:{...form,...(!connection?{password}:{})}});accept(next,true);setPassword('');},connection?t('Reglas actualizadas.','Rules updated.'):t('Gmail conectado. Se revisarán los avisos que lleguen a partir de ahora.','Gmail connected. Alerts received from now on will be checked.'));}}>
    <h3>{connection?t('Reglas de lectura','Reading rules'):t('Conecta tu Gmail','Connect your Gmail')}</h3>
    <label>{t('Correo de Gmail','Gmail address')}<input type="email" name="gmailEmail" value={form.email} required readOnly={!!connection} disabled={controlsDisabled} onChange={e=>change('email',e.target.value)} placeholder="tu.correo@gmail.com"/></label>
    {!connection&&<><label>{t('Contraseña de aplicación de Google','Google app password')}<input type="password" name="gmailAppPassword" value={password} required autoComplete="new-password" disabled={controlsDisabled} onChange={e=>setPassword(e.target.value)} placeholder="abcd efgh ijkl mnop"/></label><p className="hint">{t('Usa una contraseña de aplicación de 16 letras, con verificación en dos pasos activada. No uses tu contraseña habitual.','Use a 16-letter app password with 2-Step Verification enabled. Do not use your regular password.')} <a href="https://myaccount.google.com/apppasswords" target="_blank" rel="noreferrer">{t('Crear en Google ↗','Create in Google ↗')}</a></p></>}
    <label>{t('Remitentes exactos de tu banco','Exact bank sender addresses')}<textarea name="bankSenders" rows="2" value={form.senders} required disabled={controlsDisabled} onChange={e=>change('senders',e.target.value)} placeholder="avisos@tubanco.com"/><small>{t('Copia la dirección real del aviso. Una por línea, máximo 10.','Copy the actual address from the alert. One per line, up to 10.')}</small></label>
    <div className="form-grid"><label>{t('Etiqueta del importe','Amount label')}<input required maxLength="50" value={form.amountLabel} disabled={controlsDisabled} onChange={e=>change('amountLabel',e.target.value)}/></label><label>{t('Separador decimal','Decimal separator')}<select value={form.decimal} disabled={controlsDisabled} onChange={e=>change('decimal',e.target.value)}><option value=".">1,234.56</option><option value=",">1.234,56</option></select></label><label>{t('Palabra de gasto','Expense keyword')}<input required maxLength="50" value={form.expenseWord} disabled={controlsDisabled} onChange={e=>change('expenseWord',e.target.value)}/></label><label>{t('Palabra de entrada','Income keyword')}<input maxLength="50" value={form.incomeWord} disabled={controlsDisabled} onChange={e=>change('incomeWord',e.target.value)}/></label></div>
    <label>{t('Etiqueta de referencia única','Unique reference label')}<input maxLength="50" value={form.referenceLabel} disabled={controlsDisabled} onChange={e=>change('referenceLabel',e.target.value)}/></label>
    <p className="hint">{t('Ajusta estas palabras al texto de tu banco. Se admite un importe explícito con USD, DOP, RD$, EUR, €, MXN o COP; un símbolo $ solo se deja pendiente.','Match these words to your bank’s text. One explicit amount with USD, DOP, RD$, EUR, €, MXN or COP is supported; a bare $ is left pending.')}</p>
    <label className="toggle-row"><input type="checkbox" checked={form.automatic} disabled={controlsDisabled} onChange={e=>change('automatic',e.target.checked)}/><span><strong>{t('Registrar automáticamente','Record automatically')}</strong><small>{t('Solo avisos claros, firmados y con referencia única. Los demás quedan por revisar.','Only clear, signed alerts with a unique reference. Others await review.')}</small></span></label>
    {connection?<label className="toggle-row"><input type="checkbox" checked={form.enabled} disabled={controlsDisabled} onChange={e=>change('enabled',e.target.checked)}/><span>{t('Mantener la revisión horaria activa','Keep hourly checks active')}</span></label>:<label className="toggle-row"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{t('Autorizo a esta app a leer los avisos de los remitentes indicados.','I authorize this app to read alerts from the listed senders.')}</span></label>}
    <button className="button primary" disabled={controlsDisabled||!data?.available}>{busy?t('Conectando / guardando…','Connecting / saving…'):connection?t('Guardar reglas','Save rules'):t('Conectar Gmail','Connect Gmail')}</button>
   </form>
   <details className="mail-preview"><summary>{t('Probar con el texto de un aviso','Test an alert’s text')}</summary><p className="hint">{t('Pega el texto sin datos privados. Esta prueba no guarda movimientos ni verifica la firma del correo.','Paste the text without private data. This test does not save movements or verify email signatures.')}</p><textarea aria-label={t('Texto del aviso','Alert text')} rows="5" value={sample} onChange={e=>setSample(e.target.value)} placeholder={'Consumo aprobado\nMonto: DOP 1,250.00\nReferencia: ABC12345'}/><button className="button secondary" disabled={busy||!sample} onClick={()=>run(async()=>{const result=await api('/mail/preview',{method:'POST',body:{...form,text:sample}});setPreview(result.preview);},t('Prueba completada. No se modificó el saldo.','Test complete. Your balance is unchanged.'))}>{t('Interpretar ejemplo','Parse sample')}</button>{preview&&<div className="sample-result">{preview.candidate?<><strong>{preview.candidate.type==='expense'?t('Gasto','Expense'):t('Entrada','Income')}: {money(preview.candidate.amountCents,preview.candidate.currency)} {preview.candidate.currency}</strong><p>{t('Comprueba que el importe y el tipo coincidan con tu aviso.','Check that the amount and type match your alert.')}</p></>:<p>{issue(preview.issue)}</p>}</div>}</details>
  </div><div className="mail-activity">
   <div className="mail-activity-heading"><h3>{t('Actividad del correo','Email activity')}</h3>{connection&&<button className="text-button" disabled={busy||connection.checking||!connection.enabled||queued} onClick={()=>run(async()=>{await api('/mail/check',{method:'POST',body:{}});setQueued(true);setTimeout(()=>{if(alive.current)setQueued(false);},60000);accept(await api('/mail'));},t('Revisión solicitada. La actividad se actualizará en unos segundos.','Check requested. Activity will update in a few seconds.'))}><Icon name="refresh" size={15}/>{connection.checking?t('Revisando…','Checking…'):t('Revisar ahora','Check now')}</button>}</div>
   {connection&&<><p className="hint">{t('Última revisión','Last check')}: {stamp(connection.last_check)}<br/>{t('Próxima revisión','Next check')}: {connection.enabled?stamp(connection.next_check):t('En pausa','Paused')}</p>{connection.last_error&&<p className="form-error">{error(connection.last_error)}</p>}</>}
   <p className="hint">{t('Se usa la fecha de recepción (UTC). Puedes editarla después en Movimientos. Se muestran hasta 100 avisos, priorizando pendientes.','Receipt date (UTC) is used. You can edit it later in Movements. Up to 100 alerts are shown, pending first.')}</p>
   {!data?.events.length&&<div className="mail-empty"><span className="icon-tile pale"><Icon name="mail" size={28}/></span><h3>{t('Tu próxima compra aparecerá aquí.','Your next purchase will appear here.')}</h3><p>{t('Conecta Gmail, revisa las reglas y activa el registro automático cuando el ejemplo se interprete correctamente.','Connect Gmail, check the rules, and enable automatic recording once your sample is parsed correctly.')}</p></div>}
   <div className="mail-events">{data?.events.map(event=><article className="mail-event" key={event.id}><div className="mail-event-top"><span className={`event-status ${event.status}`}>{event.status==='applied'?t('Registrado','Recorded'):event.status==='dismissed'?t('Omitido','Dismissed'):t('Por revisar','To review')}</span><time>{stamp(event.received_at)}</time></div><h4>{event.subject||t('Sin asunto','No subject')}</h4><small>{event.sender}</small>{event.candidate&&<strong className={event.candidate.type==='expense'?'negative':'positive'}>{event.candidate.type==='expense'?'−':'+'}{money(event.candidate.amountCents,event.candidate.currency)} {event.candidate.currency}</strong>}{event.status==='pending'&&<><p>{issue(event.issue)}</p><div className="mail-event-actions">{event.candidate&&event.issue!=='DUPLICATE_REFERENCE'&&<button className="button secondary compact" disabled={busy} onClick={()=>setConfirm({id:event.id,action:'apply',label:`${event.candidate.type==='expense'?t('Descontar','Subtract'):t('Añadir','Add')} ${money(event.candidate.amountCents,event.candidate.currency)} ${event.candidate.currency}`})}>{t('Revisar y registrar','Review and record')}</button>}<button className="text-button" disabled={busy} onClick={()=>setConfirm({id:event.id,action:'dismiss',label:t('Omitir este aviso sin modificar el saldo','Dismiss this alert without changing the balance')})}>{t('Omitir','Dismiss')}</button></div></>}{confirm?.id===event.id&&<div className="inline-confirm"><p>{confirm.label}?</p><button className="button primary compact" disabled={busy} onClick={()=>{const selection=confirm;run(async()=>{accept(await api('/mail/review',{method:'POST',body:selection}));onChanged();},t('Aviso actualizado.','Alert updated.'));}}>{t('Confirmar','Confirm')}</button><button className="text-button" onClick={()=>setConfirm(null)}>{t('Cancelar','Cancel')}</button></div>}</article>)}</div>
   {connection&&<div className="mail-disconnect">{confirm?.action==='disconnect'?<div className="inline-confirm"><p>{t('Se borrará la contraseña guardada. Los movimientos y el historial se conservan.','The saved password will be deleted. Movements and history are kept.')}</p><button className="button danger-soft" disabled={busy} onClick={()=>run(async()=>{accept(await api('/mail/disconnect',{method:'POST',body:{}}),true);setConsent(false);},t('Gmail desconectado.','Gmail disconnected.'))}>{t('Confirmar desconexión','Confirm disconnect')}</button><button className="text-button" onClick={()=>setConfirm(null)}>{t('Cancelar','Cancel')}</button></div>:<button className="text-button" disabled={busy} onClick={()=>setConfirm({action:'disconnect'})}>{t('Desconectar Gmail','Disconnect Gmail')}</button>}</div>}
  </div></div>
 </section>;
}
