import { useEffect, useMemo, useRef, useState } from 'react';
import { Icon } from './components/Icon';
import { Modal } from './components/Modal';
import { ActivityChart } from './components/ActivityChart';
import { GoalCard } from './components/GoalCard';
import { AuthScreen } from './components/AuthScreen';
import { EntryForm } from './components/EntryForm';
import { AccountDrawer } from './components/AccountDrawer';
import { MailSettings } from './components/MailSettings';
import { ThemePicker } from './lib/theme';
import { ProfileForm } from './components/ProfileForm';
import { MonthlyRegister } from './components/MonthlyRegister';
import { RateEditor } from './components/RateEditor';
import { GoalEditor, PasswordForm } from './components/AccountForms';
import { LedgerTable } from './components/LedgerTable';
import { usePwa } from './lib/usePwa';
import { useI18n, categoryName } from './lib/i18n';
import { api } from './lib/api';
import { CATEGORIES, STORAGE_KEY, LEGACY_KEY, totals, today, sortMovements, filterMovements, demoState, csvExport } from './lib/finance';
import { emptyLedger, displayLedger, validateLedger, readBackup, mergeLedger } from './lib/ledger';

function download(text, filename, type = 'application/json') {
  const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
export default function App() {
  const { t,error,setLanguage }=useI18n();
  const [user,setUser]=useState(null);const [snapshot,setSnapshot]=useState(null);const [loading,setLoading]=useState(true);const [serviceError,setServiceError]=useState('');const [busy,setBusy]=useState(false);
  const saving=useRef(false);const epoch=useRef(0);const pwa=usePwa();
  function expired(){epoch.current++;setUser(null);setSnapshot(null);setServiceError('');}
  async function loadSession(knownUser){
    const current=++epoch.current;setLoading(true);setServiceError('');
    try{const account=knownUser||((await api('/auth/me')).user);const fresh=await api('/state');if(current!==epoch.current)return;setUser(account);setLanguage(account.language);setSnapshot(fresh);}
    catch(e){if(current!==epoch.current)return;if(e.code==='UNAUTHORIZED'){setUser(null);setSnapshot(null);}else setServiceError(error(e));}
    finally{if(current===epoch.current)setLoading(false);}
  }
  useEffect(()=>{loadSession();return()=>{epoch.current++;};},[]);
  async function save(ledger,revision){
    if(saving.current)return error('BUSY');saving.current=true;setBusy(true);
    try{const next=validateLedger(ledger);const result=await api('/state',{method:'PUT',body:{ledger:next,revision}});setSnapshot(result);setServiceError('');return null;}
    catch(e){if(e.code==='UNAUTHORIZED')expired();else if(e.code==='CONFLICT'){try{setSnapshot(await api('/state'));}catch(refreshError){if(refreshError.code==='UNAUTHORIZED')expired();else setServiceError(error(refreshError));}}else if(['NETWORK_ERROR','DATABASE_UNAVAILABLE'].includes(e.code))setServiceError(error(e));return error(e);}
    finally{saving.current=false;setBusy(false);}
  }
  useEffect(()=>{if(!user)return;const current=epoch.current;let running=false;const refresh=async()=>{if(saving.current||running||document.hidden)return;running=true;try{const next=await api('/state');if(current===epoch.current&&!saving.current)setSnapshot(old=>old&&next.revision>old.revision?next:old);}catch(e){if(e.code==='UNAUTHORIZED')expired();}finally{running=false;}};const timer=setInterval(refresh,60000);window.addEventListener('focus',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);};},[user?.id]);
  async function logout(){if(saving.current)return;setBusy(true);try{await api('/auth/logout',{method:'POST',body:{}});expired();}catch(e){setServiceError(error(e));}finally{setBusy(false);}}
  if(loading&&!snapshot)return <main className="loading-page"><img src="./icons/logo.svg" width="58" height="58" alt="Ahorra+"/><h1>{t('Preparando tu espacio…','Preparing your space…')}</h1><p>{t('Conectando con tus datos.','Connecting to your data.')}</p></main>;
  if(!user||!snapshot)return <AuthScreen onLogin={loadSession} initialError={serviceError}/>;
  return <Workspace user={user} snapshot={snapshot} busy={busy||loading} serviceError={serviceError} save={save} reload={()=>loadSession(user)} logout={logout} pwa={pwa} expired={expired} onProfile={updated=>{setUser(updated);setLanguage(updated.language);}}/>;
}

function Workspace({user,snapshot,busy,serviceError,save,reload,logout,pwa,onProfile,expired}){
  const {t,language,locale,money,date,error}=useI18n();
  const nav=[['resumen',t('Resumen','Overview'),'grid'],['movimientos',t('Movimientos','Movements'),'arrows'],['registro',t('Registro mensual','Monthly register'),'calendar'],['meta',t('Mi meta','My goal'),'target'],['ajustes',t('Ajustes','Settings'),'settings']];
  const validView=()=>nav.some(([id])=>id===location.hash.slice(1))?location.hash.slice(1):'resumen';
  const [accountOpen,setAccountOpen]=useState(false);const [view,setView]=useState(validView);const [modal,setModal]=useState(null);const [modalError,setModalError]=useState('');const [notice,setNotice]=useState(null);const [hidden,setHidden]=useState(false);const [demo,setDemo]=useState(false);const [page,setPage]=useState(1);const [filters,setFilters]=useState({query:'',type:'all',category:'all',month:''});const [languageBusy,setLanguageBusy]=useState(false);
  const [hasLegacy,setHasLegacy]=useState(()=>{try{return !!(localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY));}catch{return false;}});
  const inputFile=useRef(null);const undo=useRef(null);const ledger=snapshot.ledger;
  const shown=useMemo(()=>demo?demoState(new Date(),language):displayLedger(ledger),[ledger,demo,language]);const sum=totals(shown.movements);const monthly=totals(shown.movements.filter(m=>m.date.startsWith(today().slice(0,7))));
  const rows=useMemo(()=>filterMovements(shown.movements,filters),[shown,filters]);const pages=Math.max(1,Math.ceil(rows.length/10));const fmt=n=>hidden?'••••••':money(n,shown.currency);const locked=busy||!!serviceError;const editsDisabled=locked||demo;
  useEffect(()=>{const hash=()=>{setView(validView());if(location.hash==='#nuevo'){setModal({type:'entry',revision:snapshot.revision});}};window.addEventListener('hashchange',hash);hash();return()=>window.removeEventListener('hashchange',hash);},[]);
  useEffect(()=>{setPage(1);},[filters,demo]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),notice.failure?10000:6500);return()=>clearTimeout(timer);},[notice]);
  function notify(message,failure=false,canUndo=false){setNotice({message,failure,canUndo});}
  function open(type,extra={}){setModalError('');setModal({type,revision:snapshot.revision,...extra});}
  function close(){if(busy)return;setModal(null);setModalError('');if(location.hash==='#nuevo')location.hash='resumen';}
  function go(id){setView(id);location.hash=id;window.scrollTo({top:0,behavior:'instant'});}
  function add(){if(locked){notify(error('NETWORK_ERROR'),true);return;}setDemo(false);open('entry');}
  async function commit(next,message){const result=await save(next,modal?.revision??snapshot.revision);if(!result){setModal(null);setModalError('');if(location.hash==='#nuevo')location.hash='resumen';notify(message);}return result;}
  async function saveEntry(m){return commit({...ledger,movements:modal.movement?ledger.movements.map(old=>old.id===m.id?m:old):[...ledger.movements,m]},t('Movimiento guardado en PostgreSQL.','Movement saved to PostgreSQL.'));}
  async function remove(){const m=modal.movement;const result=await save({...ledger,movements:ledger.movements.filter(row=>row.id!==m.id)},modal.revision);if(result){setModalError(result);return;}undo.current=m;setModal(null);notify(t('Movimiento eliminado.','Movement deleted.'),false,true);}
  async function restore(){const m=undo.current;if(!m)return;const result=await save({...ledger,movements:[...ledger.movements,m]},snapshot.revision);if(result)notify(result,true);else{undo.current=null;notify(t('Movimiento recuperado.','Movement restored.'));}}
  function exportBackup(){download(JSON.stringify({app:'ahorra-plus',exportedAt:new Date().toISOString(),...ledger},null,2),`ahorra-plus-${today()}.json`);notify(t('Respaldo preparado.','Backup prepared.'));}
  function prepareImport(text,filename){try{const imported=readBackup(text,ledger.currency);const merged=mergeLedger(ledger,imported);open('import',{...merged,filename});}catch(e){notify(error(e),true);}}
  async function importFile(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;if(f.size>10*1024*1024){notify(error('FILE_TOO_LARGE'),true);return;}try{prepareImport(await f.text(),f.name);}catch(e){notify(error(e),true);}}
  function migrateLocal(){try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem(LEGACY_KEY);if(!raw){setHasLegacy(false);return;}prepareImport(raw,t('Datos de la versión anterior','Previous version data'));}catch(e){notify(error(e),true);}}
  async function install(){if(pwa.canInstall)await pwa.install();else open('install');}
  async function switchLanguage(value){setLanguageBusy(true);try{const result=await api('/profile',{method:'PATCH',body:{language:value}});onProfile(result.user);}catch(e){notify(error(e),true);if(e.code==='UNAUTHORIZED')expired();}finally{setLanguageBusy(false);}}
  const heading={resumen:[t('Cada ahorro cuenta.','Every saving counts.'),t('Un vistazo a tus ahorros y a lo que estás construyendo.','A look at your savings and what you are building.')],movimientos:[t('Tus movimientos.','Your movements.'),t('Entradas y salidas, con cada detalle en su lugar.','Money in and money out, with every detail in place.')],registro:[t('Tu mes, en dos tiempos.','Your month, in two halves.'),t('Consulta las entradas y los gastos de cada quincena.','Review income and expenses for each half of the month.')],meta:[t('Eso que quieres lograr.','What you want to achieve.'),t('Un propósito para cada pequeño paso.','A purpose for every small step.')],ajustes:[t('Tu espacio, a tu manera.','Your space, your way.'),t('Tu perfil, idioma, moneda y datos en un solo lugar.','Your profile, language, currency and data in one place.')]};
  return <div className="app-shell"><a className="skip-link" href="#main-content">{t('Saltar al contenido','Skip to content')}</a><aside className="sidebar"><a className="brand" href="#resumen"><img src="./icons/logo.svg" width="40" height="40" alt=""/><div><strong>Ahorra<span>+</span></strong><small>{t('PEQUEÑOS PASOS. GRANDES METAS.','SMALL STEPS. BIG GOALS.')}</small></div></a><p className="nav-label">{t('MI ESPACIO','MY SPACE')}</p><nav aria-label={t('Navegación principal','Main navigation')}>{nav.map(([id,label,icon])=><a href={`#${id}`} key={id} className={view===id?'active':''} aria-current={view===id?'page':undefined}><Icon name={icon}/><span>{label}</span>{view===id&&<span className="active-dot"/>}</a>)}</nav><div className="sidebar-bottom"><div className="install-card"><span className="install-symbol"><Icon name="monitor" size={24}/></span><strong>{t('Tus ahorros, a un clic.','Your savings, one click away.')}</strong><p>{t('Ahorra+ también vive en tu escritorio.','Ahorra+ belongs on your desktop, too.')}</p><button onClick={install}>{pwa.installed?t('App instalada','App installed'):t('Instalar aplicación','Install app')}<Icon name="up" size={16}/></button></div><button className="sidebar-export" onClick={exportBackup} disabled={demo}><Icon name="download" size={18}/>{t('Exportar respaldo','Export backup')}</button><div className="local-note"><Icon name="shield" size={16}/><span>{t('Tu cuenta. Tus ahorros.','Your account. Your savings.')}</span></div></div></aside>
    <div className="workspace"><header className="topbar"><div className="breadcrumbs"><span>{t('Mi espacio','My space')}</span><Icon name="chevron" size={13}/><strong>{nav.find(([id])=>id===view)?.[1]}</strong></div><div className="topbar-right"><span className={`connection ${serviceError?'is-offline':''}`}><span/>{busy?t('Guardando / conectando…','Saving / connecting…'):serviceError?t('Sin conexión al servidor','Server unavailable'):'PostgreSQL'}</span><button className="icon-button" onClick={reload} disabled={busy||!!modal} aria-label={t('Actualizar datos','Refresh data')}><Icon name="refresh" size={18}/></button><button className="icon-button" onClick={()=>setHidden(!hidden)} aria-label={hidden?t('Mostrar importes','Show amounts'):t('Ocultar importes','Hide amounts')} aria-pressed={hidden}><Icon name={hidden?'eyeOff':'eye'} size={19}/></button><button className="profile-button" onClick={()=>setAccountOpen(true)} aria-expanded={accountOpen} aria-haspopup="dialog" aria-label={t('Mi perfil','My profile')}>{user.avatar?<img src={user.avatar} alt=""/>:<span>{user.name.slice(0,1).toUpperCase()}</span>}</button></div></header>
    <main id="main-content" tabIndex="-1">{demo&&<div className="notice demo-notice"><span><Icon name="sparkles"/>{t('Modo de ejemplo · Datos ficticios, separados de tu cuenta.','Demo mode · Fictional data, separate from your account.')}</span><button className="text-button" onClick={()=>setDemo(false)}>{t('Volver a mis datos','Back to my data')}</button></div>}{serviceError&&<div className="notice error-notice" role="alert"><p>{serviceError}</p><button className="text-button" onClick={reload} disabled={busy}>{t('Reconectar','Reconnect')}</button></div>}{pwa.update&&<div className="notice"><span>{t('Hay una nueva versión disponible.','A new version is available.')}</span><button className="text-button" disabled={busy||!!modal} onClick={pwa.applyUpdate}>{t('Actualizar aplicación','Update app')}</button></div>}
    <div className="page-heading"><div><p className="eyebrow">{t('HOLA','HELLO')}, {user.name.toLocaleUpperCase(locale)}</p><h1>{heading[view][0]}</h1><p>{heading[view][1]}</p></div>{view!=='ajustes'&&<button className="button primary" disabled={locked} onClick={add}><Icon name="plus" size={19}/>{demo?t('Empezar con mis datos','Start with my data'):t('Nuevo movimiento','New movement')}</button>}</div>
    {(view==='resumen'||view==='movimientos')&&<section className="stats-grid" aria-label={t('Resumen de ahorros','Savings overview')}><article className="balance-card"><div className="balance-decoration" aria-hidden="true"><span/><span/><span/></div><div className="stat-top"><span>{t('Saldo disponible','Available balance')}</span><Icon name="wallet"/></div><strong className="balance-value">{fmt(sum.balance)}<small>{shown.currency}</small></strong><div className="balance-bottom"><span className="balance-badge"><span/>{t('Tu ahorro, hoy','Your savings, today')}</span><span>{shown.movements.length} {t('movimientos','movements')}</span></div></article>{[['income',t('Total guardado','Total saved'),'up'],['expense',t('Total retirado','Total withdrawn'),'down']].map(([key,label,icon])=><article className="stat-card" key={key}><div className="stat-top"><span>{label}</span><span className={`stat-arrow ${key}`}><Icon name={icon} size={18}/></span></div><strong>{fmt(sum[key])}</strong><div className="stat-bottom"><span className={`stat-pill ${key}`}>{fmt(monthly[key])}</span><span>{t('este mes','this month')}</span></div></article>)}</section>}
    {view==='resumen'&&<><div className="dashboard-grid"><ActivityChart movements={shown.movements} currency={shown.currency} hidden={hidden} onAdd={add}/><GoalCard goal={shown.goal} balance={sum.balance} currency={shown.currency} hidden={hidden} demo={editsDisabled} onEdit={()=>open('goal')}/></div><section className="panel transactions-panel"><div className="panel-heading"><div><h2>{t('Últimos movimientos','Recent movements')}</h2><p>{t('Los pequeños pasos de tu día a día','The small steps in your everyday life')}</p></div><button className="text-button" onClick={()=>go('movimientos')}>{t('Ver todos','View all')}<Icon name="right" size={16}/></button></div><LedgerTable rows={sortMovements(shown.movements).slice(0,5)} currency={shown.currency} hidden={hidden}/>{!shown.movements.length&&<div className="empty-demo-button"><button className="button secondary" onClick={()=>setDemo(true)}>{t('Ver un ejemplo','View a demo')}</button></div>}</section><div className="gentle-note"><Icon name="leaf" size={17}/><span>{t('Un poco hoy, más posibilidades mañana.','A little today, more possibilities tomorrow.')}</span></div></>}
    {view==='movimientos'&&<section className="panel transactions-panel history-panel"><div className="panel-heading"><div><h2>{t('Historial de movimientos','Movement history')} <span className="count-badge">{rows.length}</span></h2><p>{t('Tus registros, guardados en tu cuenta.','Your records, saved to your account.')}</p></div><button className="button secondary compact" disabled={demo||!rows.length} onClick={()=>download(csvExport(rows,shown.currency,language),`ahorra-plus-${today()}.csv`,'text/csv;charset=utf-8')}><Icon name="download" size={16}/>CSV</button></div><div className="filters"><label className="search-field"><Icon name="search" size={18}/><input aria-label={t('Buscar movimientos','Search movements')} placeholder={t('Buscar un movimiento…','Search movements…')} value={filters.query} onChange={e=>setFilters({...filters,query:e.target.value})}/></label><select aria-label={t('Filtrar por tipo','Filter by type')} value={filters.type} onChange={e=>setFilters({...filters,type:e.target.value})}><option value="all">{t('Todos los tipos','All types')}</option><option value="income">{t('Entradas','Income')}</option><option value="expense">{t('Salidas','Expenses')}</option></select><select aria-label={t('Filtrar por categoría','Filter by category')} value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="all">{t('Todas las categorías','All categories')}</option>{Object.keys(CATEGORIES).map(key=><option value={key} key={key}>{categoryName(key,t)}</option>)}</select><input type="month" aria-label={t('Filtrar por mes','Filter by month')} value={filters.month} onChange={e=>setFilters({...filters,month:e.target.value})}/><button className="text-button" onClick={()=>setFilters({query:'',type:'all',category:'all',month:''})}>{t('Limpiar','Clear')}</button></div><LedgerTable rows={rows.slice((Math.min(page,pages)-1)*10,Math.min(page,pages)*10)} currency={shown.currency} hidden={hidden} disabled={editsDisabled} onEdit={id=>open('entry',{movement:ledger.movements.find(m=>m.id===id)})} onDelete={id=>open('delete',{movement:ledger.movements.find(m=>m.id===id)})}/><div className="table-footer"><span>{rows.length} {t('resultados','results')} · {t('Balance filtrado','Filtered net')}: <strong>{fmt(totals(rows).balance)}</strong></span><div><button className="icon-button" aria-label={t('Página anterior','Previous page')} disabled={page<=1} onClick={()=>setPage(page-1)}><Icon name="left"/></button><span>{Math.min(page,pages)} / {pages}</span><button className="icon-button" aria-label={t('Página siguiente','Next page')} disabled={page>=pages} onClick={()=>setPage(page+1)}><Icon name="chevron"/></button></div></div></section>}
    {view==='registro'&&<MonthlyRegister movements={shown.movements} currency={shown.currency} hidden={hidden}/>}
    {view==='meta'&&<div className="goal-view"><GoalCard goal={shown.goal} balance={sum.balance} currency={shown.currency} hidden={hidden} large demo={editsDisabled} onEdit={()=>open('goal')}/><section className="goal-story"><p className="eyebrow">{t('A TU RITMO','AT YOUR OWN PACE')}</p><h2>{t('Hoy un hábito. Mañana, una posibilidad.','A habit today. A possibility tomorrow.')}</h2><p>{t('Define un objetivo, registra tus movimientos y observa cómo cada aporte te acerca.','Set a goal, track your movements and watch each contribution bring you closer.')}</p><div className="goal-facts"><div><Icon name="wallet"/><span>{t('Disponible para tu meta','Available for your goal')}<strong>{fmt(Math.max(0,sum.balance))}</strong></span></div>{shown.goal&&<div><Icon name="target"/><span>{t('Te falta para llegar','Remaining to reach your goal')}<strong>{fmt(Math.max(0,shown.goal.targetCents-sum.balance))}</strong></span></div>}</div></section></div>}
    {view==='ajustes'&&<div className="settings-grid"><MailSettings onChanged={reload}/><section className="panel settings-panel"><div className="settings-title"><span className="icon-tile green"><Icon name="settings"/></span><div><h2>{t('Mi cuenta','My account')}</h2><p>{t('Un espacio con tu nombre.','A space with your name on it.')}</p></div></div><ProfileForm user={user} onSaved={onProfile} onSessionExpired={expired}/></section><section className="panel settings-panel"><div className="settings-title"><span className="icon-tile purple"><Icon name="layers"/></span><div><h2>{t('Idioma y moneda','Language and currency')}</h2><p>{t('Tus números, en tu idioma.','Your numbers, in your language.')}</p></div></div><label className="setting-label">{t('Idioma de la aplicación','App language')}<select value={language} disabled={languageBusy} onChange={e=>switchLanguage(e.target.value)}><option value="es">Español</option><option value="en">English</option></select></label><div className="settings-divider"/><ThemePicker/><div className="settings-divider"/><h3>{t('Moneda de visualización','Display currency')}: {ledger.currency}</h3><p className="muted">{t('El saldo, el historial y la meta se convierten con las tasas guardadas en tu cuenta.','Your balance, history and goal are converted using the rates saved to your account.')}</p><button className="button primary" disabled={editsDisabled} onClick={()=>open('rates')}>{t('Cambiar moneda y tasas','Change currency and rates')}</button><p className="hint">{ledger.rateInfo.source==='manual'?t('Tasas manuales / de ejemplo. Revisa las tasas antes de usarlas.','Manual / example rates. Review rates before using them.'):t('Tasas de ExchangeRate-API.','Rates from ExchangeRate-API.')} {ledger.rateInfo.date&&new Date(ledger.rateInfo.date).toLocaleDateString(locale)}</p><div className="settings-divider"/><button className="button secondary" onClick={()=>{setDemo(!demo);go('resumen');}}>{demo?t('Salir del ejemplo','Exit demo'):t('Ver un ejemplo','View a demo')}</button></section>
    <section className="panel settings-panel"><div className="settings-title"><span className="icon-tile blue"><Icon name="shield"/></span><div><h2>{t('Tus datos en PostgreSQL','Your data in PostgreSQL')}</h2><p>{t('Vinculados a tu cuenta, sin caducidad diaria.','Connected to your account, with no daily expiration.')}</p></div></div><p className="muted">{t('Borrar los datos del navegador no elimina tus registros en la base de datos. Inicia sesión para recuperarlos. Exporta respaldos periódicamente.','Clearing browser data does not delete your database records. Sign in to recover them. Export backups regularly.')}</p><div className="settings-buttons"><button className="button primary" disabled={demo} onClick={exportBackup}><Icon name="download" size={17}/>{t('Exportar respaldo','Export backup')}</button><button className="button secondary" disabled={editsDisabled} onClick={()=>inputFile.current.click()}><Icon name="upload" size={17}/>{t('Importar respaldo','Import backup')}</button></div><input className="sr-only" type="file" accept=".json,application/json" ref={inputFile} onChange={importFile} aria-label={t('Seleccionar respaldo JSON','Select JSON backup')}/><p className="hint">{t('Los respaldos conservan las monedas originales y tus tasas. La importación agrega registros y omite duplicados idénticos.','Backups preserve original currencies and your rates. Import adds records and skips identical duplicates.')}</p>{hasLegacy&&<button className="button secondary" disabled={editsDisabled} onClick={migrateLocal}>{t('Migrar datos de este navegador','Migrate data from this browser')}</button>}</section>
    <section className="panel settings-panel"><div className="settings-title"><span className="icon-tile pale"><Icon name="shield"/></span><div><h2>{t('Acceso a tu cuenta','Account access')}</h2><p>{t('Actualiza tu contraseña.','Update your password.')}</p></div></div><PasswordForm/><div className="settings-divider"/><button className="button secondary" onClick={logout} disabled={busy}>{t('Cerrar sesión','Sign out')}</button></section>
    <section className="panel settings-panel"><div className="settings-title"><span className="icon-tile purple"><Icon name="monitor"/></span><div><h2>{t('Ahorra+ en tu escritorio','Ahorra+ on your desktop')}</h2><p>{t('Tu app, siempre a mano.','Your app, always within reach.')}</p></div></div><p className="muted">{t('Instala la app para abrirla en su propia ventana. Iniciar sesión y guardar requiere conexión con tu servidor.','Install the app to open it in its own window. Signing in and saving require a connection to your server.')}</p><div className="pwa-status"><Icon name={pwa.ready?'check':'info'} size={17}/>{pwa.ready?t('Interfaz lista para abrir sin conexión','App shell ready to open offline'):pwa.development?t('Usa npm start para probar la instalación.','Use npm start to test installation.'):pwa.error?t('No se pudo preparar la instalación. Vuelve a abrir la app con el servidor disponible.','Installation could not be prepared. Reopen the app with the server available.'):t('Preparando la instalación…','Preparing installation…')}</div><button className="button secondary" onClick={install}>{t('Instalar aplicación','Install app')}</button></section>
    <section className="panel settings-panel reset-panel"><div className="settings-title"><span className="icon-tile pink"><Icon name="trash"/></span><div><h2>{t('Empezar de nuevo','Start fresh')}</h2><p>{t('Tú tienes el control.','You are in control.')}</p></div></div><p className="muted">{t('Elimina los movimientos y la meta de tu cuenta en PostgreSQL. Conserva tu perfil. Descarga un respaldo antes.','Delete your account’s movements and goal from PostgreSQL. Keep your profile. Download a backup first.')}</p><button className="button danger-soft" disabled={editsDisabled} onClick={()=>open('reset')}>{t('Restablecer mis datos','Reset my data')}</button></section></div>}
    <footer className="page-footer"><span>Ahorra+ · {t('Un poco hoy, más posibilidades mañana.','A little today, more possibilities tomorrow.')}</span>{ledger.rateInfo.source==='ExchangeRate-API'?<a href="https://www.exchangerate-api.com" target="_blank" rel="noreferrer">Rates By Exchange Rate API</a>:<span><Icon name="shield" size={13}/>PostgreSQL · {t('Tu cuenta','Your account')}</span>}</footer></main></div>
    {accountOpen&&<AccountDrawer user={user} onSaved={onProfile} expired={expired} onClose={()=>setAccountOpen(false)} logout={logout} busy={busy} onLanguage={switchLanguage} languageBusy={languageBusy} onMail={()=>{setAccountOpen(false);go('ajustes');setTimeout(()=>document.getElementById('bank-mail')?.scrollIntoView({behavior:'smooth',block:'start'}),100);}}/>}
    <button className="mobile-add" onClick={add} disabled={locked||!!modal||accountOpen} aria-label={t('Añadir movimiento','Add movement')}><Icon name="plus" size={24}/><span>{t('Registrar','Add')}</span></button>
    {modal?.type==='entry'&&<Modal title={modal.movement?t('Editar movimiento','Edit movement'):t('Un nuevo paso.','A new step.')} onClose={close}><EntryForm movement={modal.movement} currency={ledger.currency} onSave={saveEntry} onClose={close} busy={busy}/></Modal>}
    {modal?.type==='goal'&&<Modal title={t('Tu meta, a tu manera.','Your goal, your way.')} onClose={close}><GoalEditor goal={ledger.goal} currency={ledger.currency} onSave={goal=>commit({...ledger,goal},t('Meta guardada en PostgreSQL.','Goal saved to PostgreSQL.'))} onClose={close} busy={busy}/></Modal>}
    {modal?.type==='rates'&&<Modal title={t('Tus ahorros en otra moneda.','Your savings in another currency.')} onClose={close}><RateEditor ledger={ledger} onSave={next=>commit(next,t('Moneda y tasas actualizadas.','Currency and rates updated.'))} onClose={close} busy={busy}/></Modal>}
    {modal?.type==='delete'&&<Modal title={t('¿Eliminar este movimiento?','Delete this movement?')} onClose={close}><div className="confirmation-detail"><Icon name="trash"/><div><strong>{modal.movement.reason}</strong><p>{date(modal.movement.date)} · {money(modal.movement.amountCents,modal.movement.currency)} {modal.movement.currency}</p></div></div><p className="muted">{t('Se actualizará tu saldo. Puedes deshacerlo desde el aviso inmediato.','Your balance will update. You can undo from the immediate notification.')}</p>{modalError&&<p className="form-error" role="alert">{modalError}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={close}>{t('Cancelar','Cancel')}</button><button className="button danger" disabled={busy} onClick={remove}>{t('Eliminar movimiento','Delete movement')}</button></div></Modal>}
    {modal?.type==='import'&&<Modal title={t('Tu respaldo está listo.','Your backup is ready.')} subtitle={modal.filename} onClose={close}><div className="import-summary"><div><strong>{modal.added}</strong><span>{t('registros nuevos','new records')}</span></div><div><strong>{modal.skipped}</strong><span>{t('duplicados omitidos','duplicates skipped')}</span></div></div><p className="muted">{t('Se agregan a la cuenta con la que has iniciado sesión. Los registros actuales se conservan. Los archivos antiguos sin moneda usan la moneda seleccionada.','Records will be added to the signed-in account. Existing records are preserved. Old files without a currency use the selected currency.')}</p>{modalError&&<p className="form-error" role="alert">{modalError}</p>}<div className="modal-actions"><button className="button secondary" disabled={busy} onClick={close}>{t('Cancelar','Cancel')}</button><button className="button primary" disabled={busy} onClick={async()=>{const result=await commit(modal.ledger,t('Respaldo guardado en PostgreSQL.','Backup saved to PostgreSQL.'));if(result)setModalError(result);}}>{t('Confirmar importación','Confirm import')}</button></div></Modal>}
    {modal?.type==='reset'&&<Modal title={t('Empezar de nuevo.','Start fresh.')} onClose={close}><p className="muted">{t('Se borrarán los movimientos y la meta de esta cuenta en la base de datos.','This account’s movements and goal will be deleted from the database.')}</p><button className="button secondary reset-export" onClick={exportBackup}>{t('Exportar antes de borrar','Export before deleting')}</button><form className="form" onSubmit={async e=>{e.preventDefault();if(busy)return;if(new FormData(e.target).get('confirm')!=='BORRAR'){setModalError(t('Escribe BORRAR para confirmar.','Type BORRAR to confirm.'));return;}const result=await commit({...ledger,movements:[],goal:null},t('Datos restablecidos.','Data reset.'));if(result)setModalError(result);}}><label>{t('Escribe BORRAR para confirmar','Type BORRAR to confirm')}<input name="confirm" required autoComplete="off" placeholder="BORRAR"/></label>{modalError&&<p className="form-error" role="alert">{modalError}</p>}<div className="modal-actions"><button className="button secondary" type="button" disabled={busy} onClick={close}>{t('Cancelar','Cancel')}</button><button className="button danger" disabled={busy}>{t('Borrar mis datos','Delete my data')}</button></div></form></Modal>}
    {modal?.type==='install'&&<Modal title={t('Tus ahorros, a un clic.','Your savings, one click away.')} onClose={close}><div className="install-preview"><img src="./icons/logo.svg" width="64" height="64" alt=""/><div><strong>Ahorra+</strong><span>{t('Tu espacio para ahorrar','Your space to save')}</span></div></div><ol className="install-steps"><li><strong>Chrome / Edge</strong><p>{t('Pulsa el icono de instalación en la dirección o usa el menú para instalar esta página como aplicación.','Use the install icon in the address bar or the browser menu to install this page as an app.')}</p></li><li><strong>Android / iPhone / iPad</strong><p>{t('Usa el menú o Compartir → Añadir a pantalla de inicio.','Use the menu or Share → Add to Home Screen.')}</p></li><li><strong>Mac · Safari</strong><p>{t('Archivo → Añadir al Dock, si está disponible.','File → Add to Dock, if available.')}</p></li></ol><div className="notice install-note">{t('Mantén el servidor y PostgreSQL encendidos para iniciar sesión y guardar. Tus datos están en tu cuenta, no en el acceso directo.','Keep the server and PostgreSQL running to sign in and save. Your data belongs to your account, not the shortcut.')}</div><p className="hint">{t('La instalación requiere HTTPS o localhost.','Installation requires HTTPS or localhost.')}</p></Modal>}
    {notice&&<div className={`toast ${notice.failure?'toast-error':''}`} role={notice.failure?'alert':'status'}><Icon name={notice.failure?'info':'check'} size={19}/><span>{notice.message}</span>{notice.canUndo&&<button disabled={busy} onClick={restore}>{t('Deshacer','Undo')}</button>}<button className="icon-button" onClick={()=>setNotice(null)} aria-label={t('Cerrar aviso','Dismiss notice')}><Icon name="close" size={16}/></button></div>}
  </div>;
}
